name: CI build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build Docker
        run: docker build -t local .
      - name: Run CMake
        run: docker run -v `pwd`:/app -w /app local -c "cmake -S . -B build"
      - name: Build all
        run: docker run -v `pwd`:/app -w /app local -c "cmake --build build"
      - name: Run tests
        run: |
          cd ./build/bin
          for name in ./test_*; do
              docker run -v `pwd`:/app -w /app local -c "$name"
              if [ $? -ne 0 ]; then
                  echo "Build failed on $name"
                  exit 1
              fi
          done

